### ISSUE TITLE
Add setuptools

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/distributed-feedstock#108]
In https://github.com/dask/distributed/pull/3305 we added an import of `pkg_resources`. So we should add `setuptools` (which includes `pkg_resources`) as a runtime dependency in the next release

**Comment by marcelotrevisani** [comment]
Sure, thanks for letting us know about it!
Probably if we do not add it, the build will fail for the next release
Let's keep it in mind for the next release! Thanks!
