### ISSUE TITLE
Update dependencies in next release 

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/distributed-feedstock#113]
This issue is a reminder to update the following dependencies for the next release:

- Minimum `tblib` version to `1.6.0` (xref https://github.com/dask/distributed/pull/3451) 
- For Python < 3.8 the minimum `tornado` version is 5, while for Python >= 3.8 we have a minimum `tornado` version of 6.0.3 (xref https://github.com/dask/distributed/pull/3249)

**Comment by jrbourbeau** [comment]
Closed by https://github.com/conda-forge/distributed-feedstock/pull/115

**Comment by jakirkham** [comment]
Thanks @jrbourbeau! 😄
