### ISSUE TITLE
Pin openssl in next release

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/distributed-feedstock#121]
xref https://github.com/dask/distributed/issues/3588

**Comment by jjhelmus** [comment]
Pinning to openssl 1.1.1d will ensure all users have all distributed users have an OpenSSL version that is vulnerable  CVE that has been fixed.  

Rather than this can an issue be opened in the openssl-feedstock so that the underlying issue can be investigated and fixed.

**Comment by jrbourbeau** [comment]
I may have opened this issue prematurely. Discussion is still going on in the linked `distributed` issue. I opened this issue primarily as a reminder to update the feedstock here in accordance with whatever we end up deciding to over in https://github.com/dask/distributed/issues/3588
