### ISSUE TITLE
Update `doc_source_url` to use `main`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/distributed-feedstock#193]
Currently this URL specifies `master`, but we have renamed it to `main`. Would be good to update the URL here as well to reflect this

https://github.com/conda-forge/distributed-feedstock/blob/823d9c5491fc9ad1a4e9fe111840fa4743033614/recipe/meta.yaml#L76

**Comment by jakirkham** [comment]
cc @charlesbluca @jrbourbeau

**Comment by jrbourbeau** [comment]
Good catch. Updating to `main` sounds good. I'll plan to make this update in the next release unless someone feels it should be updated before then
