### ISSUE TITLE
Disabling PyPy

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/distributed-feedstock#201]
Recently the Dask Community decided to drop PyPy support. Given this, what is the best way for us to disable PyPy support? We can add a `skip` to the recipe to disable these builds.

Though as discussed in issues ( https://github.com/regro/cf-scripts/issues/1044 ) ( https://github.com/regro/cf-scripts/issues/1386 ), we don't have a great way to opt-out of migrations and this can have downstream effects.

Given this, am raising this issue to solicit feedback ( cc @conda-forge/core ) on how we should handle this here and the proceed with next steps.

cc @jrbourbeau @mrocklin

**Comment by jakirkham** [comment]
Admittedly this may be less of an issue given we were able to move to `noarch` somewhat recently ( https://github.com/conda-forge/distributed-feedstock/pull/199 ). Not sure if there is a good way for `noarch` packages to error when installing with `pypy`

**Comment by beckermr** [comment]
If you opt out then downstream packages that need pypy and dask have no choice. Mark the prs as drafts.

**Comment by jakirkham** [comment]
Think we added PyPy previously ( https://github.com/conda-forge/distributed-feedstock/pull/155 ). So Idk if there is a way to back that out as it were

**Comment by hmaarrfk** [comment]
This might also be tied to accendental merges of PRs for migrations:
https://github.com/conda-forge/lintel-feedstock/pull/15#issuecomment-1083373804

**Comment by mattip** [comment]
Is supporting pypy such a burden that it is worth actively blocking? Has it caused problems?

**Comment by hmaarrfk** [comment]
to be honest. with the pypy38 migration, now might be the best time to simply delete the yaml file.

**Comment by mrocklin** [comment]
It's just that there haven't been any known users, and we're trying to be a
little bit more focused.  There's a question that arises of "would this
affect PyPy users?" that we'd prefer not to have to think about.
