### ISSUE TITLE
Remove recent push?

### ISSUE THREAD

**Issue by mrocklin** [conda-forge/distributed-feedstock#25]
So apparently the recent release that we pushed out was missing some critical files.  Is there a way to remove these packages from anaconda.org?

**Comment by martindurant** [comment]
You can remove files that you own.
I don't know who would have ownership rights on packages pushed by conda-forge. It could also be done by direct manipulation of the DB by continuum, I suppose.

**Comment by mrocklin** [comment]
Well I *hope* that I don't have the ability to remove arbitrary files through association with Continuum.  

I agree with you though that I think the question is who has ownership rights over conda-forge packages.  My guess is that anaconda.org doesn't give sufficiently fine-grained permissions here to allow conda-forge to allow all maintainers to have access to their particular packges.

**Comment by jakirkham** [comment]
I have labeled the recent release of distributed as `broken`. The files are still in the `conda-forge` channel, but they will not be pulled in by default unless someone is using this non-standard label. Does this affect `dask` as well or is this only an issue with `distributed`? Also is there something off about where the release was cut or is this an issue with the recipe itself?

**Comment by mrocklin** [comment]
Dask is fine.

The main issue is that we were missing files in our MANIFEST.

Is there a way that we can do this ourselves in the future?

**Comment by jakirkham** [comment]
As a workaround, could publish this release based off of a GitHub tarball. Though that doesn't really fix the PyPI release.

Only a few core members have access. TBH I don't know of an easy way to grant restricted permissions to users at scale for Anaconda.org. Also I don't think we are guaranteed a one-to-one of GitHub handles to Anaconda usernames. Though we could discuss this with the Anaconda team.

**Comment by jakirkham** [comment]
> TBH I don't know of an easy way to grant restricted permissions to users at scale for Anaconda.org. Also I don't think we are guaranteed a one-to-one of GitHub handles to Anaconda usernames. Though we could discuss this with the Anaconda team.

Have raised this as issue ( https://github.com/Anaconda-Platform/support/issues/129 ). Sorry for the slow turnaround on elevating this.

**Comment by jakirkham** [comment]
Is this ok to close now?
