### ISSUE TITLE
Require pyyaml

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/distributed-feedstock#38]
It seems this is used for loading configuration files. So maybe it should be added as a requirement.

**Comment by mrocklin** [comment]
No objection from me if it is a common dependency

**Comment by jakirkham** [comment]
I noticed it was being used to load the config. It appears to be [imported in a `try`...`except`]( https://github.com/dask/distributed/blob/1.19.3/distributed/config.py#L156 ), but it is used without a [check here]( https://github.com/dask/distributed/blob/1.19.3/distributed/config.py#L63 ). So maybe it is already a hard dependency?

**Comment by mrocklin** [comment]
That function is, I think, only called within the try-except

**Comment by mrocklin** [comment]
That being said, I don't really mind depending on it

**Comment by jakirkham** [comment]
You’re right. Overlooked the `else`. 🤦‍♂️

It seems reasonable as a dependency in `conda-forge`. I don’t know what the wheels situation is with `pyyaml`. So it may or may not be a good general requirement for PyPI packages.

**Comment by mrocklin** [comment]
Makes sense.  I've added pyyaml to the latest release PR.  Once that merges this should be done.

**Comment by jakirkham** [comment]
Thanks @mrocklin.

**Comment by mrocklin** [comment]
Thanks for the suggestion
